from flask import Flask, request, jsonify
import psycopg2

app = Flask(__name__)

# Setup your DB connection here (adjust with your DB details)
conn = psycopg2.connect(
    host="your-db-host",
    database="your-db-name",
    user="your-db-user",
    password="your-db-password"
)
cur = conn.cursor()

@app.route('/')
def home():
    return 'Hello from NetLog Flask App!'

@app.route('/log', methods=['POST'])
def log_data():
    data = request.get_json()
    message = data.get('message')

    if not message:
        return jsonify({"error": "Missing message"}), 400

    # Insert message into your DB table (adjust table name and columns)
    cur.execute("INSERT INTO logs (message) VALUES (%s)", (message,))
    conn.commit()

    return jsonify({"status": "success", "message": message}), 201

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
