#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3
  - python3-pip

runcmd:
  - pip3 install flask
  - mkdir -p /opt/netlog_app
  - |
    cat << EOF > /opt/netlog_app/app.py
    from flask import Flask
    app = Flask(__name__)

    @app.route('/')
    def home():
        return 'Hello from NetLog Flask App!'

    if __name__ == '__main__':
        app.run(host='0.0.0.0', port=5000)
    EOF

  - |
    cat << EOF > /etc/systemd/system/netlog.service
    [Unit]
    Description=NetLog Flask App
    After=network.target

    [Service]
    ExecStart=/usr/bin/python3 /opt/netlog_app/app.py
    Restart=always
    User=azureuser

    [Install]
    WantedBy=multi-user.target
    EOF

  - systemctl daemon-reload
  - systemctl enable netlog
  - systemctl start netlog
