#cloud-config
package_update: true
packages:
  - postgresql
  - postgresql-contrib

runcmd:
  - sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/12/main/postgresql.conf
  - echo "host all all 10.0.1.0/24 md5" >> /etc/postgresql/12/main/pg_hba.conf

  - systemctl stop postgresql || true
  - systemctl start postgresql
  - systemctl enable postgresql

  - sudo -u postgres psql -c "CREATE DATABASE netlog_db;"
  - sudo -u postgres psql -c "CREATE USER netlog_user WITH ENCRYPTED PASSWORD '${db_password}';"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE netlog_db TO netlog_user;"
